name: Workflow A - Run Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay to spread requests
        run: |
          SEED=$((RANDOM % 20 + 5))
          echo "Sleeping for $SEED seconds before running scraper..."
          sleep $SEED

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        run: python scraper.py

      - name: Zip output CSV (if exists)
        if: success() && hashFiles('court_scrape_results.csv') != ''
        run: |
          zip output.zip court_scrape_results.csv || true
          echo "ZIPPED_FILE=output.zip" >> $GITHUB_ENV

      - name: Upload zipped results
        if: success() && env.ZIPPED_FILE != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIPPED_FILE }}
          path: ${{ env.ZIPPED_FILE }}
